export const GET_GITHUB_COMPONENT_START = "GET_GITHUB_COMPONENT_START";
export const GET_GITHUB_COMPONENT_SUCCESS = "GET_GITHUB_COMPONENT_SUCCESS";
export const GET_GITHUB_COMPONENT_ERROR = "GET_GITHUB_COMPONENT_ERROR";
export const GET_ALL_GITHUB_CATEGORIES_START = "GET_ALL_GITHUB_CATEGORIES_START";
export const GET_ALL_GITHUB_CATEGORIES_SUCCESS = "GET_ALL_GITHUB_CATEGORIES_SUCCESS";
export const GET_ALL_GITHUB_CATEGORIES_ERROR = "GET_ALL_GITHUB_CATEGORIES_ERROR";

function getGithubAllCategories( bom ){
    return {
        type : GET_ALL_GITHUB_CATEGORIES_START
    }
}

export default {
    GET_GITHUB_COMPONENT_START,
    GET_GITHUB_COMPONENT_SUCCESS,
    GET_GITHUB_COMPONENT_ERROR,
    GET_ALL_GITHUB_CATEGORIES_START,
    GET_ALL_GITHUB_CATEGORIES_SUCCESS,
    GET_ALL_GITHUB_CATEGORIES_ERROR,
    getGithubAllCategories
}