name: Tag Application

on: 
  push:
    branches:
      - master

jobs:

  Tag-on-push:
    runs-on: windows-latest

    steps:

      - name: checkout
        uses: actions/checkout@v1

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'

      - name: package-version-to-git-tag
        uses: azu/action-package-version-to-git-tag@v1
        with:
          github_token: ${{ secrets.github_token }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.github_token }}
          tags : true

      - name: npm install / run webpack
        working-directory: ${{ github.workspace }}
        run: |
          npm install
          npm run webpack
        env:
          CI: true

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          github_token: ${{ secrets.github_token }}